### ISSUE TITLE
GetChannelModerators() does not work

### ISSUE THREAD

**Issue by Axeedd** [TwitchLib/TwitchLib.Client#255]
I do something like this

```csharp
_twitchClient.OnModeratorsReceived += _twitchClient_OnModeratorsReceived;
_twitchClient.Connect();

private void _twitchClient_OnModeratorsReceived(object sender, OnModeratorsReceivedArgs e)
{
	foreach (var mod in e.Moderators)
	{
		Console.WriteLine(mod);
	}
}
```

```csharp
var twitchChannel = "...";
_twitchClient.JoinChannel(twitchChannel);
_twitchClient.GetChannelModerators(twitchChannel);
```

And nothing happens... Using debugger I see that event OnModeratorsReceived doesn't fire in my case

**Comment by Mahsaap** [comment]
Put join channel in onconnected event, to ensure timing is correct.
Make sure the token you are using, has moderator in the channel your trying to get the mods list from.
Also hook into the onlog event if you can, this "could" help debug more.

**Comment by Hampo** [comment]
`GetChannelModerators` no longer works due to Twtich removing that commands, `.mod` being one of them. You now need to use [Get Moderators](https://dev.twitch.tv/docs/api/reference#get-moderators), which can be found in [TwitchLib.Api](https://github.com/TwitchLib/TwitchLib.Api) at `API.Helix.Moderation.GetModeratorsAsync`.

**Comment by Axeedd** [comment]
> Put join channel in onconnected event, to ensure timing is correct. (if your doing this right after connecting) Make sure the token you are using, has moderator in the channel your trying to get the mods list from. Also hook into the onlog event if you can, this "could" help debug more.

Thanks for your reply.

The code I provided is simplified version of what is actually happening. I completely sure that everything is ok with timings in real scenario.
I subscribed to OnLog event and this is what I got: (I replaced actual Twitch channel with `<twitch-channel>`)
```
TwitchClient::OnLog: Received: @msg-id=unrecognized_cmd :tmi.twitch.tv NOTICE #<twitch-channel> :Unrecognized command: /mods
TwitchClient::OnLog: Unaccounted for: @msg-id=unrecognized_cmd :tmi.twitch.tv NOTICE #<twitch-channel> :Unrecognized command: /mods (please create a TwitchLib GitHub issue :P)
```

I also checked the code in two different Twitch channels: where I am mod and where I am not. No difference

**Comment by swiftyspiffy** [comment]
>So you need to get a user access token for each channel where you want to get list of mods. That's a lot of work and it seems wrong to me, because on the Twitch website you can just use /mods command in any chat. And you don't have to be a mod or even a follower

This is correct. This is an intentional change by Twitch, as documented here: https://discuss.dev.twitch.com/t/deprecation-of-chat-commands-through-irc/40486 . Twitch is working on moving chat commands on the website to gql. Likewise chat actions for third parties are being moved from irc to helix.  

So, with the deprecation above, getting mods via chat commands via irc for third parties is no longer possible. To get mods, you must either get it manually via the website, or via the API endpoint as documented here: https://dev.twitch.tv/docs/api/reference/#get-moderators which requires `channel:manage:moderators`.

Additionally, i believe for TwitchLib, the Client code related to getting channel moderators via irc has since been removed. This should be the state in the dev branch (and soon master).

**Comment by swiftyspiffy** [comment]
Will close this since i believe things are working as expected. Feel free to comment and I can reopen if you think things are not working as expected.
