### ISSUE TITLE
Timeout - Couple changes

### ISSUE THREAD

**Issue by Mahsaap** [TwitchLib/TwitchLib.Client#76]
Use FromSeconds() instead of TotalSeconds.
Possible some vaildations of the contents submitted for Timespan
Parse result to int (twitch requires a whole number)

**Comment by 3ventic** [comment]
Few options here:
1) Automatically round to nearest valid integer (1-1209600)
2) Take an integer of total seconds instead of a TimeSpan (breaking change, I don't like this)
3) Send a formatted string and throw an argument exception for <1 second duration

I'll elaborate on 3, which is my personal preference for this. Twitch accepts a "rich" duration like "0h2m15s" for 2 minutes and 15 seconds (135 seconds). We should use this, and throw an argument exception, if the duration is less than 1 second.
```
client.SendMessage(channel, $".timeout {viewer} {duration.Days}d{duration.Hours}h{duration.Minutes}m{duration.Seconds}s {message}", dryRun);
```
